// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk1FO6OAcp8JDnSsuGGLgXGAMaeJeebU4',
    appId: '1:287064741750:web:cc5b8e8d92f7bde5ae8c57',
    messagingSenderId: '287064741750',
    projectId: 'riderfirebase-e359a',
    authDomain: 'riderfirebase-e359a.firebaseapp.com',
    storageBucket: 'riderfirebase-e359a.appspot.com',
    measurementId: 'G-E43ZJT0R1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnZzl2fcamkDxSUQ9Taza_ORyAIQm5qlw',
    appId: '1:287064741750:android:0d4716c7709dbe42ae8c57',
    messagingSenderId: '287064741750',
    projectId: 'riderfirebase-e359a',
    storageBucket: 'riderfirebase-e359a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhg0fRNJrWF8ctz5Ucve1j8Zbg02k3JnA',
    appId: '1:287064741750:ios:c5f5a96b9b6df7dbae8c57',
    messagingSenderId: '287064741750',
    projectId: 'riderfirebase-e359a',
    storageBucket: 'riderfirebase-e359a.appspot.com',
    iosBundleId: 'com.example.firebaseRider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhg0fRNJrWF8ctz5Ucve1j8Zbg02k3JnA',
    appId: '1:287064741750:ios:c5f5a96b9b6df7dbae8c57',
    messagingSenderId: '287064741750',
    projectId: 'riderfirebase-e359a',
    storageBucket: 'riderfirebase-e359a.appspot.com',
    iosBundleId: 'com.example.firebaseRider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk1FO6OAcp8JDnSsuGGLgXGAMaeJeebU4',
    appId: '1:287064741750:web:9c46c2092f9e515cae8c57',
    messagingSenderId: '287064741750',
    projectId: 'riderfirebase-e359a',
    authDomain: 'riderfirebase-e359a.firebaseapp.com',
    storageBucket: 'riderfirebase-e359a.appspot.com',
    measurementId: 'G-2ZYCPJTMY6',
  );
}
